run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/bierlingm/beats
  misspell:
    locale: US
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (database/sql.Rows).Close
      - (database/sql.Stmt).Close
      - (*database/sql.Tx).Rollback
      - os.Remove

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - internal/store/sqlite.go  # Unused, future feature
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
